# Generated by Django 6.0.1 on 2026-01-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для ответа')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ТС')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID прибора (из AutoGRAPH)')),
                ('expected_consumption_idle', models.FloatField(default=2.0, verbose_name='Расход на стоянке (л/ч)')),
                ('expected_consumption_move', models.FloatField(default=25.0, verbose_name='Расход в движении (л/100км)')),
                ('sensors_count', models.IntegerField(default=1, verbose_name='Количество ДУТ')),
            ],
        ),
        migrations.CreateModel(
            name='FuelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('drain', 'Слив'), ('refill', 'Заправка'), ('overrun', 'Перерасход'), ('error', 'Сбой датчика')], max_length=10)),
                ('timestamp', models.DateTimeField(verbose_name='Время события')),
                ('volume', models.FloatField(verbose_name='Объем (литры)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено пользователем')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.vehicle')),
            ],
        ),
    ]
